AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  rexample:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: script.handler
      Runtime: provided
      CodeUri: .
      Description: ''
      MemorySize: 1024
      Timeout: 300
      Role: 'arn:aws:iam::608494368293:role/s3-textract-lambdas'
      Layers:
        - 'arn:aws:lambda:us-east-2:608494368293:layer:r-pdftools:1'
        - 'arn:aws:lambda:us-east-2:608494368293:layer:r-libs:1'
        - 'arn:aws:lambda:us-east-2:131329294410:layer:r-runtime-3_6_0:12'
